#!/bin/sh
# * change-owner
#   Define quién manda
#   ssh git@host change-owner repo "Hacklab"

set -e

repo=$1; shift

test -d "${repo}".git && \
git config -f "${repo}.git/config" "gitweb.owner" "${@}"

exit $?
