#!/bin/sh
# * change-description
#   Cambia la descripcion del projecto, necesita archivo description en el proyecto
#   ssh git@host change-description repo "description"

set -e

repo=$1; shift

echo "${@}" > ${repo}.git/description

exit $?
