#!/bin/sh
# * delete-repo
#   Allows users to delete repositories permanently
#   ssh git@host delete-repo repo1 repo2 ...

set -e

for repo in $@; do
    if [ -z "$repo" ]; then continue; fi

    # lo and behold absolute horror
    rm -rf "$repo".git
done
