#!/bin/sh
# * fetch-mirrors
#   Actualiza el `mirrors` (espejos) creados con `mirror`
#   ssh git@host fetch-mirrors

set -e

# Find all mirrors
~/git-shell-commands/mirrors | \
  while read _mirror; do

    pushd "$_mirror" >/dev/null

    git remote update

    popd >/dev/null

done

exit $?
